---
apiVersion: v1
kind: ConfigMap
metadata:
  name: route
  annotations:
    alertmanager.net/route: "true"
    alertmanager.net/id: "0"
data:
  test_route.yaml: |-
    - receiver: default
      group_by:
        - instance
        - alertname
        - pod_name
        - namespace
        - node
        - job
      routes:
      - receiver: test1
        match_re:
          receiver: .*test1.*
        continue: true
      - receiver: test2
        match_re:
          receiver: .*test2.*
        continue: true
        routes:
        - receiver: test3
          match_re:
            kubernetes_service: .*test3.*