---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inhibit-rule
  annotations:
    alertmanager.net/inhibit_rule: "true"
    alertmanager.net/id: "0"
data:
  test_inhibit_rule.yaml: |-
    - target_match:
        test: test
        test2: test2
      source_match:
        label1: label1
        label2: label22