---
project_name: alertmanager-config-controller

release:
  github:
    owner: dbsystel
    name: alertmanager-config-controller

builds:
  - binary: alertmanager-config-controller
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archive:
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
    - LICENSE
    - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^dev:'
    - 'README'
    - Merge pull request
    - Merge branch

dockers:
  - image_templates:
      - "dbsystel/alertmanager-config-controller:latest"
      - "dbsystel/alertmanager-config-controller:{{ .Tag }}"
      - "dbsystel/alertmanager-config-controller:v{{ .Major }}.{{ .Minor }}"
