dist: trusty
sudo: required

language: go
go: '1.12.x'

services:
  - docker

install:
  - GOPATH=${TRAVIS_BUILD_DIR}/vendor/go
  - make setup

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
notifications:
  email: false

