apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "alertmanager.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: / 
            backend:
              serviceName: {{ template "alertmanager.name" . }}
              servicePort: {{ .Values.service.port }}
