apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port:  {{ .Values.service.port | quote }}
  name: {{ template "alertmanager.name" . }}
  labels:
    name: {{ template "alertmanager.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: {{ template "alertmanager.name" . }}
  selector:
    app: {{ template "alertmanager.name" . }}
